[tool.poetry]
name = "yuiko-profile"
version = "1.0.0"
description = "yuiko-profile"
authors = ["yuiko"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
